// gRPC wire protocol for ydbsql: the single SQL/ADMIN transport between
// clients, the shard manager, and cross-node forwarding.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.30.2
// source: internal/rpc/ydb.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResultPayload is the outcome of a statement.
type ResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"` // []string rows as byte-packed fields (see Row)
	Affected      int64                  `protobuf:"varint,4,opt,name=affected,proto3" json:"affected,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"` // aux data (e.g. shard advertise addr)
	ExecMs        int64                  `protobuf:"varint,6,opt,name=exec_ms,json=execMs,proto3" json:"exec_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultPayload) Reset() {
	*x = ResultPayload{}
	mi := &file_internal_rpc_ydb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultPayload) ProtoMessage() {}

func (x *ResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_ydb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultPayload.ProtoReflect.Descriptor instead.
func (*ResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_rpc_ydb_proto_rawDescGZIP(), []int{0}
}

func (x *ResultPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResultPayload) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ResultPayload) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ResultPayload) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

func (x *ResultPayload) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ResultPayload) GetExecMs() int64 {
	if x != nil {
		return x.ExecMs
	}
	return 0
}

// Row is one result row: values are flattened and may contain arbitrary
// bytes (e.g. encoded primary keys / shard range bounds), hence []byte.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_internal_rpc_ydb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_ydb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_internal_rpc_ydb_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// Request is a single SQL (or ADMIN) request.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_rpc_ydb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_ydb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_rpc_ydb_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

// Response is a server reply.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Result        *ResultPayload         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_rpc_ydb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_ydb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_rpc_ydb_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetResult() *ResultPayload {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_rpc_ydb_proto protoreflect.FileDescriptor

const file_internal_rpc_ydb_proto_rawDesc = "" +
	"\n" +
	"\x16internal/rpc/ydb.proto\x12\x05ydbgo\"\xa6\x01\n" +
	"\rResultPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x1e\n" +
	"\x04rows\x18\x03 \x03(\v2\n" +
	".ydbgo.RowR\x04rows\x12\x1a\n" +
	"\baffected\x18\x04 \x01(\x03R\baffected\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x17\n" +
	"\aexec_ms\x18\x06 \x01(\x03R\x06execMs\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"+\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"n\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12,\n" +
	"\x06result\x18\x04 \x01(\v2\x14.ydbgo.ResultPayloadR\x06result2g\n" +
	"\n" +
	"YdbService\x12*\n" +
	"\aExecute\x12\x0e.ydbgo.Request\x1a\x0f.ydbgo.Response\x12-\n" +
	"\x06Stream\x12\x0e.ydbgo.Request\x1a\x0f.ydbgo.Response(\x010\x01B\x18Z\x16ydbgo/internal/rpc;rpcb\x06proto3"

var (
	file_internal_rpc_ydb_proto_rawDescOnce sync.Once
	file_internal_rpc_ydb_proto_rawDescData []byte
)

func file_internal_rpc_ydb_proto_rawDescGZIP() []byte {
	file_internal_rpc_ydb_proto_rawDescOnce.Do(func() {
		file_internal_rpc_ydb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_ydb_proto_rawDesc), len(file_internal_rpc_ydb_proto_rawDesc)))
	})
	return file_internal_rpc_ydb_proto_rawDescData
}

var file_internal_rpc_ydb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_rpc_ydb_proto_goTypes = []any{
	(*ResultPayload)(nil), // 0: ydbgo.ResultPayload
	(*Row)(nil),           // 1: ydbgo.Row
	(*Request)(nil),       // 2: ydbgo.Request
	(*Response)(nil),      // 3: ydbgo.Response
}
var file_internal_rpc_ydb_proto_depIdxs = []int32{
	1, // 0: ydbgo.ResultPayload.rows:type_name -> ydbgo.Row
	0, // 1: ydbgo.Response.result:type_name -> ydbgo.ResultPayload
	2, // 2: ydbgo.YdbService.Execute:input_type -> ydbgo.Request
	2, // 3: ydbgo.YdbService.Stream:input_type -> ydbgo.Request
	3, // 4: ydbgo.YdbService.Execute:output_type -> ydbgo.Response
	3, // 5: ydbgo.YdbService.Stream:output_type -> ydbgo.Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_rpc_ydb_proto_init() }
func file_internal_rpc_ydb_proto_init() {
	if File_internal_rpc_ydb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_ydb_proto_rawDesc), len(file_internal_rpc_ydb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_ydb_proto_goTypes,
		DependencyIndexes: file_internal_rpc_ydb_proto_depIdxs,
		MessageInfos:      file_internal_rpc_ydb_proto_msgTypes,
	}.Build()
	File_internal_rpc_ydb_proto = out.File
	file_internal_rpc_ydb_proto_goTypes = nil
	file_internal_rpc_ydb_proto_depIdxs = nil
}
