// gRPC wire protocol for ydbsql: the single SQL/ADMIN transport between
// clients, the shard manager, and cross-node forwarding.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: internal/rpc/ydb.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YdbService_Execute_FullMethodName = "/ydbgo.YdbService/Execute"
	YdbService_Stream_FullMethodName  = "/ydbgo.YdbService/Stream"
)

// YdbServiceClient is the client API for YdbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// YdbService is the query endpoint served by every ydbgo node.
type YdbServiceClient interface {
	// Execute is a single request/response (used by one-shot clients).
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Stream is a bidirectional stream for hot clients: requests and responses
	// are matched by Request.id over one persistent HTTP/2 connection, avoiding
	// per-call stream setup.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type ydbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYdbServiceClient(cc grpc.ClientConnInterface) YdbServiceClient {
	return &ydbServiceClient{cc}
}

func (c *ydbServiceClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, YdbService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ydbServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &YdbService_ServiceDesc.Streams[0], YdbService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YdbService_StreamClient = grpc.BidiStreamingClient[Request, Response]

// YdbServiceServer is the server API for YdbService service.
// All implementations must embed UnimplementedYdbServiceServer
// for forward compatibility.
//
// YdbService is the query endpoint served by every ydbgo node.
type YdbServiceServer interface {
	// Execute is a single request/response (used by one-shot clients).
	Execute(context.Context, *Request) (*Response, error)
	// Stream is a bidirectional stream for hot clients: requests and responses
	// are matched by Request.id over one persistent HTTP/2 connection, avoiding
	// per-call stream setup.
	Stream(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedYdbServiceServer()
}

// UnimplementedYdbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYdbServiceServer struct{}

func (UnimplementedYdbServiceServer) Execute(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedYdbServiceServer) Stream(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedYdbServiceServer) mustEmbedUnimplementedYdbServiceServer() {}
func (UnimplementedYdbServiceServer) testEmbeddedByValue()                    {}

// UnsafeYdbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YdbServiceServer will
// result in compilation errors.
type UnsafeYdbServiceServer interface {
	mustEmbedUnimplementedYdbServiceServer()
}

func RegisterYdbServiceServer(s grpc.ServiceRegistrar, srv YdbServiceServer) {
	// If the following call panics, it indicates UnimplementedYdbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YdbService_ServiceDesc, srv)
}

func _YdbService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YdbServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YdbService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YdbServiceServer).Execute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _YdbService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(YdbServiceServer).Stream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YdbService_StreamServer = grpc.BidiStreamingServer[Request, Response]

// YdbService_ServiceDesc is the grpc.ServiceDesc for YdbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YdbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ydbgo.YdbService",
	HandlerType: (*YdbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _YdbService_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _YdbService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/rpc/ydb.proto",
}
